name: Test setup-python

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

  strategy:
    matrix:
      os: [macos-latest, ubuntu-latest]
  
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Verify Python version
      run: python --version
